---
# pxeboot molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0


- name: Prepare for pxeboot role
  hosts: all

  vars:
    acme_username: "www-data"  # make independent of the acme role
    vhosts:
      - name: "boot.example.com"
        default_server: true
        autoindex: true

  pre_tasks:

    - name: update apt cache
      apt:
        update_cache: true

    - name: Install ps command for Debian init.d script to function
      apt:
        name:
          - "procps"
        state: "present"

  roles:
    - nginx
